# Generated by Django 4.0.3 on 2023-05-15 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_fridge_bitter_gourd_fridge_brinjal_fridge_capsicum_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fridge',
            old_name='capsicum',
            new_name='beans',
        ),
        migrations.RenameField(
            model_name='fridge',
            old_name='green_beans',
            new_name='coriander_leaves',
        ),
        migrations.RenameField(
            model_name='fridge',
            old_name='green_peas',
            new_name='cucumber',
        ),
        migrations.RenameField(
            model_name='fridge',
            old_name='ladys_finger',
            new_name='ladyfinger',
        ),
        migrations.RenameField(
            model_name='fridge',
            old_name='onion',
            new_name='runner_beans',
        ),
        migrations.RenameField(
            model_name='fridge',
            old_name='spong_gourd',
            new_name='sponge_gourd',
        ),
        migrations.RemoveField(
            model_name='fridge',
            name='taro_root',
        ),
    ]
