# Generated by Django 4.0.3 on 2023-05-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='isvoted',
            field=models.BooleanField(default=False),
        ),
    ]
