# Generated by Django 4.0.3 on 2023-05-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_recipe_isvoted'),
    ]

    operations = [
        migrations.AddField(
            model_name='validuser',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
