# Generated by Django 4.0.3 on 2023-05-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_validuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validuser',
            name='image',
            field=models.TextField(),
        ),
    ]
